import { Group, GroupName, IconColor, Section } from "./components/types";
import {
  IconAlertTriangle,
  IconBinaryTree,
  IconBrandAws,
  IconBrandGithub,
  IconBuildingWarehouse,
  IconCheckbox,
  IconCompass,
  IconDatabase,
  IconDog,
  IconEye,
  IconFileDescription,
  IconFileText,
  IconFolderOpen,
  IconFolderSearch,
  IconHexagonNumber3,
  IconKey,
  IconLock,
  IconPlus,
  IconSettings,
  IconSettingsBolt,
  IconSettingsDollar,
  IconSquareLetterS,
  IconSum,
  IconSwitch3,
  IconTelescope,
  IconTool,
  IconTournament,
  IconUserCheck,
} from "@tabler/icons-react";

export const groups: Array<Group> = [
  {
    icon: IconDatabase,
    iconColor: IconColor.Data,
    name: GroupName.Data,
  },
  {
    icon: IconLock,
    iconColor: IconColor.Security,
    name: GroupName.Security,
  },
  {
    icon: IconBuildingWarehouse,
    iconColor: IconColor.Store,
    name: GroupName.Store,
  },
  {
    icon: IconTool,
    iconColor: IconColor.Tools,
    name: GroupName.Tools,
  },
  {
    icon: IconSettings,
    iconColor: IconColor.Settings,
    name: GroupName.Settings,
  },
];

export const sections: Array<Section> = [
  {
    icon: IconFolderOpen,
    iconColor: IconColor.Data,
    group: GroupName.Data,
    name: "Catalog",
    description: "Description of application",
    shortcut: "⌥ C",
  },
  {
    icon: IconEye,
    iconColor: IconColor.Data,
    group: GroupName.Data,
    name: "Observability",
    description: "Description of application",
    shortcut: "⌥ O",
  },
  {
    icon: IconTournament,
    iconColor: IconColor.Data,
    group: GroupName.Data,
    name: "Lineage",
    description: "Description of application",
    shortcut: "⌥ L",
  },
  {
    icon: IconSwitch3,
    iconColor: IconColor.Data,
    group: GroupName.Data,
    name: "ETL",
    description: "Description of application",
    shortcut: "⌥ E",
  },

  {
    icon: IconUserCheck,
    iconColor: IconColor.Security,
    group: GroupName.Security,
    name: "Access",
    description: "Description of application",
    shortcut: "⌥ A",
  },
  {
    icon: IconAlertTriangle,
    iconColor: IconColor.Security,
    group: GroupName.Security,
    name: "Logs",
    description: "Description of application",
    shortcut: "⌥ G",
  },
  {
    icon: IconCompass,
    iconColor: IconColor.Security,
    group: GroupName.Security,
    name: "Discovery",
    description: "Description of application",
    shortcut: "⌥ D",
  },
  {
    icon: IconFileDescription,
    iconColor: IconColor.Security,
    group: GroupName.Security,
    name: "Policies",
    description: "Description of application",
    shortcut: "⌥ P",
  },
  {
    icon: IconCheckbox,
    iconColor: IconColor.Security,
    group: GroupName.Security,
    name: "Compliance",
    description: "Description of application",
    shortcut: "⌥ Q",
  },
  {
    icon: IconBrandAws,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "AWS",
    description: "Description of application",
    shortcut: "⌥ ↑ A",
  },
  {
    icon: IconDog,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "Datadog",
    description: "Description of application",
    shortcut: "⌥ ↑ D",
  },
  {
    icon: IconSquareLetterS,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "Splunk",
    description: "Description of application",
    shortcut: "⌥ ↑ S",
  },
  {
    icon: IconHexagonNumber3,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "S3",
    description: "Description of application",
    shortcut: "⌥ ↑ 3",
  },
  {
    icon: IconBrandGithub,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "Github",
    description: "Description of application",
    shortcut: "⌥ ↑ G",
  },
  {
    icon: IconTelescope,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "datahub",
    description: "Description of application",
    shortcut: "⌥ ↑ G",
  },
  {
    icon: IconPlus,
    iconColor: IconColor.Store,
    group: GroupName.Store,
    name: "Manage Store apps",
    description: "Description of application",
    shortcut: "⌥ ↑ G",
  },

  {
    icon: IconKey,
    iconColor: IconColor.Tools,
    group: GroupName.Tools,
    name: "API Keys",
    description: "Description of application",
    shortcut: "⌥ K",
  },
  {
    icon: IconSum,
    iconColor: IconColor.Tools,
    group: GroupName.Tools,
    name: "Sigma",
    description: "Description of application",
    shortcut: "⌥ S",
  },
  {
    icon: IconBinaryTree,
    iconColor: IconColor.Tools,
    group: GroupName.Tools,
    name: "Workflow",
    description: "Description of application",
    shortcut: "⌥ W",
  },

  {
    icon: IconSettingsBolt,
    iconColor: IconColor.Settings,
    group: GroupName.Settings,
    name: "Common Setting A",
    description: "Description of application",
    shortcut: "⌥ 0",
  },
  {
    icon: IconSettingsDollar,
    iconColor: IconColor.Settings,
    group: GroupName.Settings,
    name: "Special Setting B",
    description: "Description of application",
    shortcut: "⌥ 9",
  },
];

export const commands: Array<Section> = [
  {
    icon: IconFolderSearch,
    iconColor: IconColor.Command,
    group: GroupName.Data,
    name: "catalog search",
    labels: ["Keyword"],
    description: "Search the data catalog for datasets using a keyword.",
  },
  {
    icon: IconEye,
    iconColor: IconColor.Command,
    group: GroupName.Data,
    name: "observability status",
    labels: ["Dataset"],
    description: "Check the observability status of a specific dataset.",
  },
  {
    icon: IconSwitch3,
    iconColor: IconColor.Command,
    group: GroupName.Data,
    name: "etl run",
    labels: ["Job Name"],
    description: "Run an ETL job by specifying its name.",
  },
  {
    icon: IconUserCheck,
    iconColor: IconColor.Command,
    group: GroupName.Security,
    name: "access grant",
    labels: ["User", "Resource"],
    description: "Grant access to a user for a specific resource.",
  },
  {
    icon: IconAlertTriangle,
    iconColor: IconColor.Command,
    group: GroupName.Security,
    name: "logs view",
    labels: ["Data", "Type"],
    description: "View security logs for a specific date and log type.",
  },
  {
    icon: IconFileText,
    iconColor: IconColor.Command,
    group: GroupName.Security,
    name: "policies create",
    labels: ["PolicyName", "Rules"],
    description: "Create a security policy with specified rules.",
  },
  {
    icon: IconKey,
    iconColor: IconColor.Command,
    group: GroupName.Tools,
    name: "apikeys create",
    labels: ["Name"],
    description: "Create an api key with a given name.",
  },
  {
    icon: IconSum,
    iconColor: IconColor.Command,
    group: GroupName.Tools,
    name: "sigma analyze",
    labels: ["Query"],
    description: "Analyze data using Sigma notation.",
  },
  {
    icon: IconUserCheck,
    iconColor: IconColor.Command,
    group: GroupName.Tools,
    name: "workflow start",
    labels: ["workflow"],
    description: "Start a workflow by specifying its name.",
  },
];
